=== JackKarichkovskiy/greenhouse-xml-parser/src/xmlFiles/greenhouse.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="greenhouse">
        <xs:annotation>
            <xs:documentation>To change this license header, choose License Headers in Project Properties.
                To change this template file, choose Tools | Templates
                and open the template in the editor.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plants">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="plant" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name"/>
                                        <xs:element name="soil">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="podzolic"/>
                                                    <xs:enumeration value="subterranean"/>
                                                    <xs:enumeration value="sod-podzolic"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="origin"/>
                                        <xs:element name="visualParams">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="stalkColor"/>
                                                    <xs:element type="xs:string" name="leafColor"/>
                                                    <xs:element type="xs:float" name="averageSize"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="growingTips">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="temparature">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:byte">
                                                                <xs:minInclusive value="0"/>
                                                                <xs:maxInclusive value="100"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element type="xs:boolean" name="lighting"/>
                                                    <xs:element type="xs:int" name="watering"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="multiplying">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="leaf"/>
                                                    <xs:enumeration value="stalk"/>
                                                    <xs:enumeration value="seed"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:int" name="id" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JackKarichkovskiy/greenhouse-xml-parser/src/xmlFiles/greenhouse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<greenhouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="greenhouse.xsd">
    <flowers>
        <flower id="1">
            <name>rose</name>
            <soil>sod-podzolic</soil>
            <origin>China</origin>
            <visualParams>
                <stalkColor>green</stalkColor>
                <leafColor>red</leafColor>
                <averageSize>0.45</averageSize>
            </visualParams>
            <growingTips>
                <temparature>20</temparature>
                <lighting>true</lighting>
                <watering>100500</watering>
            </growingTips>
            <multiplying>seed</multiplying>
        </flower>
        <flower id="2">
            <name>cactus</name>
            <soil>sod-podzolic</soil>
            <origin>South Africa</origin>
            <visualParams>
                <stalkColor>brown</stalkColor>
                <leafColor>none</leafColor>
                <averageSize>0.5</averageSize>
            </visualParams>
            <growingTips>
                <temparature>35</temparature>
                <watering>500</watering>
                <lighting>false</lighting>
            </growingTips>
            <multiplying>stalk</multiplying>
        </flower>
    </flowers>
</greenhouse>
